### ISSUE TITLE
关于评测结果的疑问

### ISSUE THREAD

**Issue by wang304381190** [GeorgeLuImmortal/DocLLM_reimplementation#1]
您好，请问性能比较那块两个模型是经过同样的微调了吗，baichuan2-7b用你的数据只用文本信息做sft，新模型额外用box信息做sft，保证比较的公平性。

**Comment by GeorgeLuImmortal** [comment]
是的，都只经过一样数据的微调，没有pt

**Comment by wang304381190** [comment]
但是我看论文里写的SFT没有什么特别的，只是普通的SFT呀，那这个提升来自哪里呢

**Comment by wang304381190** [comment]
SFT没有用到bbox信息吧，只是用的text？
